// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// A class that exposes all Firebase options for both Android and iOS.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoYHFDnzDxsbi7hDmdKDrUaWHLqGP9zBY',
    appId: '1:249696762983:android:83ba8b161701376966e8c2',
    messagingSenderId: '249696762983',
    projectId: 'aquabalance-9f3b5',
    storageBucket: 'aquabalance-9f3b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoYHFDnzDxsbi7hDmdKDrUaWHLqGP9zBY',
    appId: '1:249696762983:ios:YOUR-APP-ID',
    messagingSenderId: '249696762983',
    projectId: 'aquabalance-9f3b5',
    storageBucket: 'aquabalance-9f3b5.firebasestorage.app',
    iosBundleId: 'com.watertracking.aquabalance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoYHFDnzDxsbi7hDmdKDrUaWHLqGP9zBY',
    appId: '1:249696762983:windows:YOUR-APP-ID',
    messagingSenderId: '249696762983',
    projectId: 'aquabalance-9f3b5',
    storageBucket: 'aquabalance-9f3b5.firebasestorage.app',
  );
}
